USE [master]
GO

/****** Object:  Database [NHCMessaging]    Script Date: 4/23/2022 3:58:49 AM ******/
CREATE DATABASE [NHCMessaging]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NHCMessaging', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NHCMessaging.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NHCMessaging_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NHCMessaging_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NHCMessaging].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NHCMessaging] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NHCMessaging] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NHCMessaging] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NHCMessaging] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NHCMessaging] SET ARITHABORT OFF 
GO

ALTER DATABASE [NHCMessaging] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NHCMessaging] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NHCMessaging] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NHCMessaging] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NHCMessaging] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NHCMessaging] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NHCMessaging] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NHCMessaging] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NHCMessaging] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NHCMessaging] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NHCMessaging] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NHCMessaging] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NHCMessaging] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NHCMessaging] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NHCMessaging] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NHCMessaging] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NHCMessaging] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NHCMessaging] SET RECOVERY FULL 
GO

ALTER DATABASE [NHCMessaging] SET  MULTI_USER 
GO

ALTER DATABASE [NHCMessaging] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NHCMessaging] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NHCMessaging] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NHCMessaging] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NHCMessaging] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NHCMessaging] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [NHCMessaging] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NHCMessaging] SET  READ_WRITE 
GO

